### ISSUE TITLE
GLTF2Loader is out of date

### ISSUE THREAD

**Issue by nfurtwangler** [antonio-gomez/three-gltf2-loader#1]
I tried using the current npm package and it fails on the RiggedFigure sample from here:

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/RiggedFigure

I manually copied the updated GLTF2Loader code from three.js and it now supports that scene.  Issue was a change/deprecation to the skinWeight attribute (WEIGHTS_0).

i see you already have a dev branch with newer gltf2loader so it would be great to publish that on npm!

**Comment by antonio-gomez** [comment]
Hi @nfurtwangler 

Thanks for pointing this out, please refer to the latest version published at NPM (v1.1.0)

https://github.com/antonio-gomez/three-gltf2-loader/releases/tag/1.1.0
